### PR TITLE
Make Serdes less confusing

### PR DESCRIPTION
**Pull request by joan38**
Serdes is confusing IMHO:
1) We have wrappers around `Serializer`, `Deserializer` and `Serde` which are not very useful.
2) We have Serdes in 2 places `org.apache.kafka.common.serialization.Serde` and in `com.lightbend.kafka.scala.streams.DefaultSerdes`, instead we should be having only one place where to find all the Serdes.
3) The avro serde in the tests can be generic

### CODE REVIEW

**Comment by joan38** [comment]
This is ready to be reviewed @debasishg

**Comment by debasishg** [comment]
Please read the notification at the top of README. This library has been accepted for inclusion in to Apache Kafka. It's already there in the trunk and will be released along with the next release of Kafka. Hold on to your PRs and submit them against apache/kafka repo once released. It will be difficult to reconcile if we make changes here.

**Comment by joan38** [comment]
That's a good new @debasishg. Do you know if we will still be using SBT or it will be integrated to the main Gradle build?

**Comment by joan38** [comment]
This can now be closed as it's been opened on Kafka's repo with https://github.com/apache/kafka/pull/4963

**Pull request closed without merging**
